# Generated by Django 3.0.5 on 2021-01-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsmessage',
            old_name='post',
            new_name='num',
        ),
    ]
