# Generated by Django 3.0.5 on 2021-01-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20210118_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsmessage',
            name='num',
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.ClientsMessage')),
            ],
        ),
    ]
