# Generated by Django 2.2.16 on 2021-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210422_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copywriting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='copywriting',
            name='image',
            field=models.ImageField(upload_to='gallery/copywriting'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='image',
            field=models.ImageField(upload_to='gallery/electronics'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modeling_3d',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modeling_3d',
            name='image',
            field=models.ImageField(upload_to='gallery/3D_Modeling'),
        ),
        migrations.AlterField(
            model_name='web',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='web',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/web'),
        ),
    ]
