# Generated by Django 2.2.16 on 2021-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
