# Generated by Django 2.2.16 on 2021-04-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210428_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.TextField(),
        ),
    ]
