# Generated by Django 2.2.16 on 2021-04-30 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20210428_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='gallery/electronics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='web',
            name='image2',
            field=models.ImageField(blank=True, upload_to='gallery/web'),
        ),
    ]
