# Generated by Django 2.2.16 on 2021-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210430_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Copywriting',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
        migrations.DeleteModel(
            name='Modeling_3D',
        ),
        migrations.AlterField(
            model_name='web',
            name='image',
            field=models.ImageField(upload_to='gallery/web'),
        ),
    ]
