# Generated by Django 2.2.16 on 2021-05-13 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='loacation',
        ),
    ]
