# Generated by Django 2.2.16 on 2021-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210513_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('percentage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='What_i_do',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H_tag', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/myPic'),
        ),
    ]
