# Generated by Django 2.2.16 on 2021-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210513_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='what_i_do',
            name='favColor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='what_i_do',
            name='favicon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
