# Generated by Django 2.2.16 on 2021-05-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210514_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_i_do',
            name='favColor',
        ),
        migrations.RemoveField(
            model_name='what_i_do',
            name='favicon',
        ),
        migrations.AlterField(
            model_name='myskill',
            name='percentage',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='skill',
            field=models.CharField(max_length=50),
        ),
    ]
