# Generated by Django 2.2.16 on 2021-05-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210514_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myskill',
            name='percentage',
            field=models.CharField(max_length=30),
        ),
    ]
