# Generated by Django 2.2.16 on 2021-05-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20210514_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myskill',
            name='progresBar',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
