# Generated by Django 2.2.16 on 2021-05-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20210514_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='gallery/Blog')),
                ('links', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ecommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='gallery/Ecommerce')),
                ('links', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='gallery/Portfolio')),
                ('links', models.URLField(blank=True, max_length=500)),
                ('github', models.URLField(blank=True, max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Web',
        ),
    ]
